### ISSUE TITLE
Release versions compatible with 242 platform

### ISSUE THREAD

**Issue by lancelote** [JetBrains/intellij-micropython#295]
2024.2 IDE versions will be released soon.

# ToDo

* [x] #314
* [x] Create branch `241`
* [x] Switch to `242` IJ platform in `master`
* [x] Release a new plugin version for `242`

**Comment by elmot** [comment]
- [ ] Get rid of obsolete Python package manager code

**Comment by lancelote** [comment]
Extracted from the core task ...

* [ ] Search & fix compatibility issues
* [ ] Switch to Java 21 as JVM target (default version for `242` platform)
